GET http://localhost:8080/api/users

###
POST http://localhost:8080/api/users
content-type: application/json

{
    "first_name": "Luan",
    "last_name": "Vieira",
    "biography": "Software Engineer"
}